USE master;
GO
CREATE MASTER KEY ENCRYPTION BY PASSWORD = 'umb^&`g~(900*!hraco123';
GO
CREATE CERTIFICATE MyUmbracoServerCert WITH SUBJECT = 'My Umbraco DEK Certificate';
GO
USE umbraco;
GO
CREATE DATABASE ENCRYPTION KEY
WITH ALGORITHM = AES_256
ENCRYPTION BY SERVER CERTIFICATE MyUmbracoServerCert;
GO
ALTER DATABASE umbraco
SET ENCRYPTION ON;
GO